import { USER_ROLES } from 'constants/auth';

export const fakeUsersList = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708862011,
    restaurant: 'Belarus',
    role: USER_ROLES.ADMIN,
    email: 'test@test.com',
  },
  {
    id: 2,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570703862011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 3,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570704862011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 4,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708562011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 5,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708812011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 117,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708812011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 6,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708812011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 7,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708812011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
  {
    id: 8,
    first_name: 'John',
    last_name: 'Doe',
    last_seen: 1570708812011,
    restaurant: 'Jack Bao Foods',
    role: USER_ROLES.ADMIN,
  },
];

export const fakeSelectData = [
  { label: 'Afghanistan' },
  { label: 'Aland Islands' },
  { label: 'Albania' },
  { label: 'Algeria' },
  { label: 'American Samoa' },
  { label: 'Andorra' },
  { label: 'Angola' },
  { label: 'Anguilla' },
  { label: 'Antarctica' },
  { label: 'Antigua and Barbuda' },
  { label: 'Argentina' },
  { label: 'Armenia' },
  { label: 'Aruba' },
  { label: 'Australia' },
  { label: 'Austria' },
  { label: 'Azerbaijan' },
  { label: 'Bahamas' },
  { label: 'Bahrain' },
  { label: 'Bangladesh' },
  { label: 'Barbados' },
  { label: 'Belarus' },
].map(suggestion => ({
  value: suggestion.label,
  label: suggestion.label,
}));
